### ISSUE TITLE
writeProbabilityImages writes all zeros in the images

### ISSUE THREAD

**Issue by goodfood6** [deeplearningais/curfil#10]
Hi,

First of all, thank you for your great work ~~~

I just started using curfil. It seems that the program writes PNGs with the per-class probabilities(all zeros) of the prediction. I think we need to scale the probabilities from 0~1 to 0~255
in file predict.cpp line 325:
probabilityImage.setColor(x, y, c, probability);
--->
probabilityImage.setColor(x, y, c, probability * 255);

**Comment by temporaer** [comment]
thanks for the report! I can only guess that no-one was using those PNGs because they're discretized. Can you submit a pull-request?

**Comment by goodfood6** [comment]
Thanks for your super fast reply. Just submitted the change.  ;)
