### ISSUE TITLE
Compilation problem with dependency Vigra

### ISSUE THREAD

**Issue by manyaafonso** [deeplearningais/curfil#18]
I followed the instructions to install Vigra and Intel TBB, but this happens:
$cmake -DCMAKE_BUILD_TYPE=Release ..
-- Found Intel TBB
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find VIGRA (missing: VIGRA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindVIGRA.cmake:43 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:30 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!

Can you please suggest a fix? Or specify in the readme what needs to change in the CMakeLists or other files?

**Comment by temporaer** [comment]
how did you install Vigra? Maybe it's in a non-standard location? In that case, provide that location to [find_package](https://cmake.org/cmake/help/v3.0/command/find_package.html) in the [CMakeLists.txt](https://github.com/deeplearningais/curfil/blob/master/src/CMakeLists.txt#L30)

**Comment by manyaafonso** [comment]
Hi, thanks for your prompt reply. Vigra is installed to /usr/local/lib/vigra.
I added the line SET(VIGRA_DIR,"/usr/local/lib/vigra") before the line FIND_PACKAGE(VIGRA    REQUIRED), but the exact same thing happens (after deleting the CMakeCache.txt). Any help will be much appreciated!

**Comment by temporaer** [comment]
From [the documentation](https://github.com/deeplearningais/curfil/blob/master/CMakeModules/FindVIGRA.cmake), it looks to me like you should set `VIGRA_ROOT`, not `VIGRA_DIR`.

**Comment by manyaafonso** [comment]
Thanks for your inputs. Really appreciate it because something like 1% of github authors actually reply. I will try reinstalling vigra, because VIGRA_ROOT needs to be /usr/local/lib/vigra, whereas VIGRA_INCLUDE_DIR needs to be /usr/local/include/vigra. Using SET() doesn't seem to work for me.

**Comment by temporaer** [comment]
Instead of reinstalling, feel free to modify [the library searching script](https://github.com/deeplearningais/curfil/blob/master/CMakeModules/FindVIGRA.cmake) to suit your needs, e.g. by introducing additional variables or just hard-coding the path (I wouldn't commit this type of change though).

**Comment by manyaafonso** [comment]
I know, its probably the correct approach to alter the cmake parameters, but I realized that I installed vigra as sudo, although their instructions say 
make
make install
which I presume is as a normal user. This might explain the problem that in the file FindVIGRA.cmake, it appends "/include" to the VIGRA_ROOT path. In my case, this would lead to "/usr/local/lib/vigra" + "/include". Many thanks for pointing me to the right direction.

**Comment by manyaafonso** [comment]
Hi again, Hannes. Hard-coding the paths in CMakeLists worked (I also needed to build ndarray separately), but now I have a new problem:

/home/linuxmintdesktop/curfil/src/curfil/random_tree.h:981:26: error: there are no arguments to ‘isnan’ that depend on a template parameter, so a declaration of ‘isnan’ must be available [-fpermissive]
             if (isnan(max) || count > max) {
                          ^
/home/linuxmintdesktop/curfil/src/curfil/random_tree.h:981:26: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from /home/linuxmintdesktop/curfil/src/curfil/random_tree_image.h:40:0,
                 from /home/linuxmintdesktop/curfil/src/curfil/random_forest_image.h:34,
                 from /home/linuxmintdesktop/curfil/src/curfil/predict.h:34,
                 from /home/linuxmintdesktop/curfil/src/curfil/predict.cpp:28:
... and many other errors all about isnan.

I noticed by using a grep that you don't have the line using vigra; anywhere.

**Comment by temporaer** [comment]
isnan is defined in namespace std in `<cmath>`: http://en.cppreference.com/w/cpp/numeric/math/isnan. You may want to prefix the calls (and PR the changes if it helps).
