### ISSUE TITLE
Could NOT find VIGRA (missing: VIGRA_INCLUDE_DIR)

### ISSUE THREAD

**Issue by selectee4all** [deeplearningais/curfil#19]
Please guide me for this error,

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find VIGRA (missing: VIGRA_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindVIGRA.cmake:43 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:30 (FIND_PACKAGE)

**Comment by selectee4all** [comment]
even vigra is installed.

**Comment by temporaer** [comment]
When you say that vigra is installed, are you referring to the package `libvigraimpex-dev` ?

**Comment by selectee4all** [comment]
Thanks, that is solved but now i have another issue,

CUDA_NVCC_FLAGS: ;-gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35
CMake Error at src/CMakeLists.txt:89 (add_subdirectory):
  add_subdirectory given source "ndarray/src/cuv" which is not an existing
  directory.


-- GIT VERSION: v1.1-11-g1cea71a
-- GIT VERSION: `1.1-11-g1cea71a'
-- Configuring incomplete, errors occurred!

**Comment by selectee4all** [comment]
Thanks alot, i have solved that issued but i have another issue now

Building CXX object src/curfil/CMakeFiles/curfil.dir/utils.cpp.o
/bin/sh: 1: g++-4.6: not found
make[2]: *** [src/curfil/CMakeFiles/curfil.dir/random_tree.cpp.o] Error 127
make[2]: *** Waiting for unfinished jobs....
/bin/sh: 1: g++-4.6: not found
make[2]: *** [src/curfil/CMakeFiles/curfil.dir/utils.cpp.o] Error 127

**Comment by selectee4all** [comment]
Thanks. This solved my issues.
