### ISSUE TITLE
only 89M GPU used

### ISSUE THREAD

**Issue by shammmmmless** [deeplearningais/curfil#22]
when I trained, there are only 89M gpu used, and nothing printed after:
  2019-Jun-03 13:17:30.415189  INFO    learning image tree ensemble. 3 trees with 20 threads
Is it correct? 7 tests were passed.

**Comment by temporaer** [comment]
what are 89M GPU? If this is a mobile (=laptop) GPU, this package isn't written for or tested on mobile GPUs.

**Comment by shammmmmless** [comment]
I run it with 1070 on Ubuntu16.04, It work with NYU dataset now, so I think the problem is about my dataset.
