### ISSUE TITLE
loading all images into memory?

### ISSUE THREAD

**Issue by tschmidt23** [deeplearningais/curfil#6]
I seem to be having memory issues with curfil_train. I have a dataset of ~6000 images, and when I run curfil_train, it tries to load all of them, gets somewhere in the 1750-1850 range, then my computer locks up and the process eventually gets killed. 

By a back of the envelope calculation, this should be approximately the number of images required to fill up the memory on my computer. Is curfil_train actually trying to load all images simultaneously into memory? If so, this would limit the number of training images to a number that is quite small by modern standards.

**Comment by temporaer** [comment]
Hi Tanner, 
Did you try using --imageCacheSize ? 

Am 22. Januar 2015 00:23:20 MEZ, schrieb Tanner Schmidt <notifications@github.com>:
>I seem to be having memory issues with curfil_train. I have a dataset
>of ~6000 images, and when I run curfil_train, it tries to load all of
>them, gets somewhere in the 1750-1850 range, then my computer locks up
>and the process eventually gets killed. 
>
>By a back of the envelope calculation, this should be approximately the
>number of images required to fill up the memory on my computer. Is
>curfil_train actually trying to load all images simultaneously into
>memory? If so, this would limit the number of training images to a
>number that is quite small by modern standards.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/deeplearningais/curfil/issues/6

-- 
Office: LBH, I.10
Phone: +49 (0) 228 73-4175

**Comment by tschmidt23** [comment]
I did, with the same result (even for very small values like 50 MB). I also monitored the GPU memory usage with nvidia-smi and it seemed fine right up until the computer locks up. It seems to be a CPU memory issue?

**Comment by temporaer** [comment]
No, there's no mechanism to prevent filling up your RAM :-/

Am 22. Januar 2015 20:10:23 MEZ, schrieb Tanner Schmidt <notifications@github.com>:
>I did, with the same result (even for very small values like 50 MB). I
>also monitored the GPU memory usage with nvidia-smi and it seemed fine
>right up until the computer locks up. It seems to be a CPU memory
>issue?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/deeplearningais/curfil/issues/6#issuecomment-71079005

-- 
Office: LBH, I.10
Phone: +49 (0) 228 73-4175

**Comment by tschmidt23** [comment]
Actually, is batch processing supported at all yet? Unless I missed something, it seems that the imageCacheSize and maxSamplesPerBatch fields of the configuration are not actually used.

**Comment by temporaer** [comment]
It's used. Both variables are put into a TrainingConfiguration object and then accessed via getters. E.g., Check for getImageCacheSize in `curfil/random_tree_image_gpu.cu:395`. 

To store the datasets I'd recommend one of the following:
- use multiple cores to unpack JPEGs (from an SSD) in parallel
- memory-map raw bitmaps using HDF5 files
it depends on the size of your dataset and how much CPU time you still have available.

To make sure training continues to be fast, you probably need to make sure that each tree needs a subset of the data that fits in RAM (or even smaller if you process multiple trees in parallel), and start loading from disk for the node processed after the current one.

Loading from disk for the node currently processed is probably going to slow you down significantly.
