### ISSUE TITLE
Problems compiling in Ubuntu 14.04 

### ISSUE THREAD

**Issue by agustingarciaflores** [deeplearningais/curfil#7]
Hi,

I'm having some trouble trying to compile your project under Ubuntu 14.04 following the steps you provide in the documentation.

First, when I execute the cmake command, I receive the following warning: 

"CMake Warning (dev) in src/ndarray/src/cuv/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "ndarray" has an INTERFACE_LINK_LIBRARIES property.  This should be
  preferred as the source of the link interface for this library but because
  CMP0022 is not set CMake is ignoring the property and using the link
  implementation as the link interface instead.

  INTERFACE_LINK_LIBRARIES:

    /usr/local/cuda-7.0/lib64/libcudart.so;ndarray

  Link implementation:

    /usr/local/cuda-7.0/lib64/libcudart.so
"

Then, when I try to execute the make command, a error in the linking with the ndarray library appears: 

"Linking CXX shared library libndarray.so
Error running link command: No such file or directory
make[2]: *** [src/ndarray/src/cuv/libndarray.so] Error 2
make[1]: *** [src/ndarray/src/cuv/CMakeFiles/ndarray.dir/all] Error 2
make: *** [all] Error 2" 

I have the same problems in a different machine with Linux Mint 17 (Linux distribution based in Ubuntu 14.04). Both distributions are running gcc 4.8.

Thanks in advance.

Agustín García.

**Comment by temporaer** [comment]
Could you try changing the hard-coded gcc version (4.6) in src/CmakeLists.txt to your version? This kludge is for an older ubuntu version and likely obsolete now.

**Comment by agustingarciaflores** [comment]
That solve the compilation problems, thanks! Sadly, I have another problem now. When I execute the ctest to see if all went well, only two test passed ("image_test" and "random_tree_test"). The other five test failed. Do you have any ideas about what's happening?

I'm using CUDA 7.0, which is running fine with other projects.

Thanks again for your support.

PS: I haven't installed the MDBQ library as is optional. Can this be related to the problem?

**Comment by temporaer** [comment]
I removed some stray asserts and fixed JSON import/export. See 3a70fd60a89e71f250fea377b0780f7013be471a and cc96317d0d7ca2b6bddc2b937a053a8fad2d2be3 for reference.
