### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by Queuecumber** [deeplearningais/curfil#8]
I'm probably doing something wrong but I can't seem to get this library to compile. It seems to be an error with ndarray.

When I run CMake I get the following warning: 

    CMake Warning (dev) at /usr/share/cmake-3.0/Modules/FindCUDA.cmake:1493 (add_library):
    Policy CMP0038 is not set: Targets may not link directly to themselves.
    Run "cmake --help-policy CMP0038" for policy details.  Use the cmake_policy
    command to set the policy and suppress this warning.

    Target "ndarray" links to itself.
    Call Stack (most recent call first):
    src/ndarray/src/cuv/CMakeLists.txt:26 (CUDA_ADD_LIBRARY)
    This warning is for project developers.  Use -Wno-dev to suppress it.

When I compile I get the following error:

    [  4%] [  8%] [ 12%] Building NVCC (Device) object     src/ndarray/src/cuv/CMakeFiles/ndarray.dir//./ndarray_generated_reference.cu.o
    Building NVCC (Device) object src/ndarray/src/cuv/CMakeFiles/ndarray.dir//./ndarray_generated_allocators.cu.o
    Building NVCC (Device) object src/ndarray/src/cuv/CMakeFiles/ndarray.dir//./ndarray_generated_memory.cu.o
    Linking CXX shared library libndarray.so
    Error running link command: No such file or directory
    src/ndarray/src/cuv/CMakeFiles/ndarray.dir/build.make:2445: recipe for target     'src/ndarray/src/cuv/libndarray.so' failed
    make[2]: *** [src/ndarray/src/cuv/libndarray.so] Error 2
    CMakeFiles/Makefile2:285: recipe for target 'src/ndarray/src/cuv/CMakeFiles/ndarray.dir/all' failed
    make[1]: *** [src/ndarray/src/cuv/CMakeFiles/ndarray.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed  
    make: *** [all] Error 2

Just for reference, I ran `cmake --help-policy CMP0038` as recommended in the cmake warning and it says: 

 > CMP0038
> -------
> 
> Targets may not link directly to themselves.
> 
> CMake 2.8.12 and lower allowed a build target to link to itself directly with
> a ``target_link_libraries()`` call. This is an indicator of a bug in
> user code.
> 
> The OLD behavior for this policy is to ignore targets which list themselves
> in their own link implementation.  The NEW behavior for this policy is to
> report an error if a target attempts to link to itself.
> 
> This policy was introduced in CMake version 3.0.  CMake version
> 3.0.2 warns when the policy is not set and uses OLD behavior.  Use
> the cmake_policy command to set it to OLD or NEW explicitly.

Any idea what I'm doing wrong?

**Comment by temporaer** [comment]
Never seen that one before. I'd guess that error could be due to a more recent cmake than the one I've tested with. 

Can you remove the linking in 
https://github.com/deeplearningais/ndarray/blob/master/src/cuv/CMakeLists.txt

...and try again? I don't have a computer with me for the next days :-/

Am 4. September 2015 21:20:10 GMT+07:00, schrieb Max Ehrlich <notifications@github.com>:
>I'm probably doing something wrong but I can't seem to get this library
>to compile. It seems to be an error with ndarray.
>
>When I run CMake I get the following warning: 
>
>CMake Warning (dev) at /usr/share/cmake-3.0/Modules/FindCUDA.cmake:1493
>(add_library):
>Policy CMP0038 is not set: Targets may not link directly to themselves.
>Run "cmake --help-policy CMP0038" for policy details.  Use the
>cmake_policy
>    command to set the policy and suppress this warning.
>
>    Target "ndarray" links to itself.
>    Call Stack (most recent call first):
>    src/ndarray/src/cuv/CMakeLists.txt:26 (CUDA_ADD_LIBRARY)
>  This warning is for project developers.  Use -Wno-dev to suppress it.
>
>When I compile I get the following error:
>
>[  4%] [  8%] [ 12%] Building NVCC (Device) object    
>src/ndarray/src/cuv/CMakeFiles/ndarray.dir//./ndarray_generated_reference.cu.o
>Building NVCC (Device) object
>src/ndarray/src/cuv/CMakeFiles/ndarray.dir//./ndarray_generated_allocators.cu.o
>Building NVCC (Device) object
>src/ndarray/src/cuv/CMakeFiles/ndarray.dir//./ndarray_generated_memory.cu.o
>    Linking CXX shared library libndarray.so
>    Error running link command: No such file or directory
>src/ndarray/src/cuv/CMakeFiles/ndarray.dir/build.make:2445: recipe for
>target     'src/ndarray/src/cuv/libndarray.so' failed
>    make[2]: *** [src/ndarray/src/cuv/libndarray.so] Error 2
>CMakeFiles/Makefile2:285: recipe for target
>'src/ndarray/src/cuv/CMakeFiles/ndarray.dir/all' failed
>  make[1]: *** [src/ndarray/src/cuv/CMakeFiles/ndarray.dir/all] Error 2
>    Makefile:127: recipe for target 'all' failed  
>    make: *** [all] Error 2
>
>Just for reference, I ran `cmake --help-policy CMP0038` as recommended
>in the cmake warning and it says: 
>
> > CMP0038
>> -------
>> 
>> Targets may not link directly to themselves.
>> 
>> CMake 2.8.12 and lower allowed a build target to link to itself
>directly with
>> a ``target_link_libraries()`` call. This is an indicator of a bug in
>> user code.
>> 
>> The OLD behavior for this policy is to ignore targets which list
>themselves
>> in their own link implementation.  The NEW behavior for this policy
>is to
>> report an error if a target attempts to link to itself.
>> 
>> This policy was introduced in CMake version 3.0.  CMake version
>> 3.0.2 warns when the policy is not set and uses OLD behavior.  Use
>> the cmake_policy command to set it to OLD or NEW explicitly.
>
>Any idea what I'm doing wrong?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/deeplearningais/curfil/issues/8

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Queuecumber** [comment]
That didn't fix the error but it did remove the warning. I think maybe that warning is not the actual problem, I'll see if I can figure out which file it's missing

**Comment by Queuecumber** [comment]
OK so I was able to get the project to build and all test pass

That being said there is definitely something wrong still

The steps I followed:

1. Remove ndarray from the build
2. Build ndarray on its own (it built fine)
3. Add the ndarray build directory as a lib directory for curfil
4. Edit every build.make and link.txt emitted by the cmake process for curfil to change 'g++-4.6' to 'g++'

That last step confuses me greatly. I don't have g++-4.6 on my machine and I've never had cmake try to use it for any other project (including when I built ndarray on its own). I suspect that is the main issue preventing a smooth build.

**Comment by temporaer** [comment]
Ok, yes, that was a workaround for an old ubuntu system. The default gcc version is set in one of the cmakelists.txt files, top level I believe. I'll remove it once I'm back.

Am 5. September 2015 20:41:11 GMT+07:00, schrieb Max Ehrlich <notifications@github.com>:
>OK so I was able to get the project to build and all test pass
>
>That being said there is definitely something wrong still
>
>The steps I followed:
>
>1. Remove ndarray from the build
>2. Build ndarray on its own (it built fine)
>3. Add the ndarray build directory as a lib directory for curfil
>4. Edit every build.make and link.txt emitted by the cmake process for
>curfil to change 'g++-4.6' to 'g++'
>
>That last step confuses me greatly. I don't have g++-4.6 on my machine
>and I've never had cmake try to use it for any other project (including
>when I built ndarray on its own). I suspect that is the main issue
>preventing a smooth build. 
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/deeplearningais/curfil/issues/8#issuecomment-137957268

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Queuecumber** [comment]
Yup I completely missed that in my reading of the build files, commenting that line out and reverting any other changes I made fixes the build for me

**Comment by tornadomeet** [comment]
@Queuecumber @temporaer i met the same problem, so how to remove the ndarray form the build and how to add ndarray build directory as a lib directory for curfil? thanks.

**Comment by tornadomeet** [comment]
@Queuecumber i just solved it as your post! by two tips:
1. i commit the line ```add_subdirectory(ndarray/src/cuv)```in curfil/src/CMakeList.txt;  so it will not copy the ndarray to build dir.
2. build ndarray alone, and copy the libndarray.so to /usr/local/lib,so when we make we can search the libndarray.so.
