### ISSUE TITLE
Only 2 tests passed CTest 

### ISSUE THREAD

**Issue by bruceko** [deeplearningais/curfil#9]
I used curfil earlier this year and I was able to complete the tasks I have.
However, I am trying to install curfil in other machine then I got some errors.
First thing is after running the CTest, I got this message.
I saw some changes but I don't know if this is normal or not.
    Start 1: image_test
1/7 Test #1: image_test .......................   Passed    0.78 sec
    Start 2: feature_generation_test
2/7 Test #2: feature_generation_test ..........***Failed    0.88 sec
    Start 3: random_tree_test
3/7 Test #3: random_tree_test .................   Passed    0.00 sec
    Start 4: random_tree_image_gpu_test
4/7 Test #4: random_tree_image_gpu_test .......***Failed    0.52 sec
    Start 5: image_cache_test
5/7 Test #5: image_cache_test .................***Failed    0.09 sec
    Start 6: import_export_test
6/7 Test #6: import_export_test ...............***Failed    0.26 sec
    Start 7: random_tree_image_test
7/7 Test #7: random_tree_image_test ...........***Failed    1.34 sec

29% tests passed, 5 tests failed out of 7

Total Test time (real) =   3.91 sec

The following tests FAILED:
	  2 - feature_generation_test (Failed)
	  4 - random_tree_image_gpu_test (Failed)
	  5 - image_cache_test (Failed)
	  6 - import_export_test (Failed)
	  7 - random_tree_image_test (Failed)
Errors while running CTest

I ignored this message and installed curfil to run the NYU example.
Then I got the other error.
Could anyone tell me how to fix them. Thanks.
2015-Sep-14 09:59:20.729077  INFO    finished loading 795 images. size in memory: 3943.65 MB
2015-Sep-14 09:59:20.729416  INFO    max samples per batch: 4661
2015-Sep-14 09:59:20.729439  INFO    image cache size: 41 images (252.2 MB)
2015-Sep-14 09:59:20.729460  INFO    trees: 3
2015-Sep-14 09:59:20.729474  INFO    training trees in parallel: 0
2015-Sep-14 09:59:20.729495  INFO    randomSeed: 4711
samplesPerImage: 4537
featureCount: 5729
minSampleCount: 204
maxDepth: 18
boxRadius: 111
regionSize: 3
thresholds: 20
maxImages: 0
imageCacheSize: 41
accelerationMode: gpu
maxSamplesPerBatch: 4661
subsamplingType: classUniform
useCIELab: 1
useDepthFilling: 0
deviceIds: [0]
ignoredColors: [0,0,0]
useDepthImages: 1
horizontalFlipping: 0
2015-Sep-14 09:59:20.729577  INFO    learning image tree ensemble. 3 trees with 8 threads
2015-Sep-14 09:59:23.064907  INFO    sampling 4 classes. 300510 samples per class with 8 threads from 795 images
2015-Sep-14 09:59:51.552866  INFO    sampled 0 pixels of class '0' RGB(0,0,0)
2015-Sep-14 09:59:51.612679  INFO    sampled 300510 pixels of class '1' RGB(181,137,0)
2015-Sep-14 09:59:51.669283  INFO    sampled 300510 pixels of class '2' RGB(7,54,66)
2015-Sep-14 09:59:51.731785  INFO    sampled 300510 pixels of class '3' RGB(147,161,161)
2015-Sep-14 09:59:51.793203  INFO    sampled 300510 pixels of class '4' RGB(203,75,22)
2015-Sep-14 09:59:51.799354  INFO    sampled 1202040 pixels for 4 classes (300510 samples/class) in 28.7345 s
2015-Sep-14 09:59:51.808080  INFO    sorting 1202040 samples
2015-Sep-14 09:59:51.912847  INFO    sorted in 104.69 ms
2015-Sep-14 10:00:17.263581  INFO    GPU Device 0: GeForce GTX 960
2015-Sep-14 10:00:17.264210  INFO    training level 1. nodes: 1
2015-Sep-14 10:00:17.272194  INFO    randomFeatureGeneration: skipped 1135664 samples
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaBindTextureToArray(colorTexture, colorTextureData): invalid texture reference
Aborted (core dumped)

**Comment by temporaer** [comment]
this looks like something I've fixed recently, are you sure you're using the current HEAD version?

**Comment by bruceko** [comment]
Yes, I did.
I followed the installation from https://github.com/deeplearningais/curfil to install curfil then I got these.
$ git show-ref --heads
f8655978e37d6614ea5b71eaf1480b02087e1e48 refs/heads/master

**Comment by bruceko** [comment]
I just find out what the problem is after replying your comment.
The link f865597 links to the update in README.md ans shows that I have to change the CUDA_ARCHITECTURE.
All 7 tests are passed after I changed that and this also fixes the second problem I have.
I am running the training now.
Thank you.

**Comment by temporaer** [comment]
ah, yes, exactly. good luck!

**Comment by jgbos** [comment]
Hi, I know this issue was closed, but I'm running into the same issue (failed test and same error on training), and the `CUDA_ARCHITECTURE` fix does not help.  Some notes:

- I've compiled off `master`
- I had to do the `ndarray` fix from  #8 
- Change g++ setting to `SET(CMAKE_CXX_COMPILER g++)`
- Machine: Centos 6.7, CUDA 8.0, gcc 4.9.2, Tesla K20c GPU

Do you know how I can debug this issue?
